<!DOCTYPE html>
<html lang="en">
<head>
    <base href="<?php echo BASE_URL ?>">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    <title>MiraSol Reservas</title>
</head>
<body>

    <!-- main header -->
  <header>
      <nav class="navbar navbar-expand-lg bg-light">
          <div class="container-fluid">
            <a class="navbar-brand" href="">Hotel MiraSol</a>
            <?php if (isset($this->user->username)): ?>
              <span class="navbar-text"><strong> <?php echo htmlspecialchars($this->user->username) ?> </strong></span>
            <?php endif ?>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="">Listado de reservas</a>
                </li>
                <?php if (isset($this->user->username)): ?>
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="addReservation">Agregar reserva</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="addClient">Agregar cliente</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="logout">Cerrar sesión</a>
                </li>
                <?php endif; ?>
                <?php if (!isset($this->user->username)): ?>
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="login">Iniciar sesión</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="signup">Registrarse</a>
                </li>
                <?php endif; ?>
              </ul>
            </div>
          </div>
      </nav>
  </header>