<?php require_once "templates/layout/header.phtml";?>

    
    <div class="card d-flex border border-primary-subtle text-center text-bg-light justify-content-center container-sm mt-2 mb-2">
        <?php if ($error): ?>
            <div class="alert alert-danger d-flex justify-content-center" role="alert">
                <?= $error ?>
            </div>
        <?php endif ?>
        <form method="POST" action="login">
            <div class="form-group m-2">
                <label for="username">Nombre de usuario</label>
                <input type="username" class="form-control" id="username" name="username" required>
            </div>
            <div class="form-group m-2">
                <label for="password">Contraseña</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <button type="sumbit" class="btn btn-primary m-2">Iniciar Sesión</button>
        </form>
    </div>

    

<?php require_once "templates/layout/footer.phtml"; 