    <?php require_once "templates/layout/header.phtml";?>



    <div class="d-flex justify-content-center mt-5">
    <div class="card d-flex border border-primary-subtle p-3 text-center text-bg-light ">
        <form action="<?php echo "edit/" . htmlspecialchars($reservation->ID_Reservation)?>" id="edit" method="POST" class="row g-3 needs-validation p-3 mt-5 mb-5 mx-5" novalidate>
            <div >
                <label for="ID_Client"><em>ID de cliente</em>: <strong><?php echo $reservation->ID_Client ?></strong></label>
                <select class="form-select text-center" name="ID_Client" id="ID_Client">
                    <?php foreach($clients as $client) : ?>
                        <option value=" <?php echo htmlspecialchars($client->ID_Client) ?>" <?php if($client->ID_Client == $reservation->ID_Client): echo "selected"; endif;?>><?php echo htmlspecialchars($client->ID_Client) . " - " . htmlspecialchars($client->Firstname) . " " . htmlspecialchars($client->Lastname)?></option>
                    <?php endforeach ?>
                </select>
            </div>
            <div >
                <label for="room_number" class="form-label" for="room_number"><em>Número de habitación</em>: <strong> <?php echo htmlspecialchars($reservation->Room_number) ?> </strong> </label>
                <input type="number" class="form-control text-center" id="room_number" value="<?php echo htmlspecialchars($reservation->Room_number) ?>" name="room_number" required  min=1 max=999 step=1>
                
            </div>
            <div >
                <label for="date" class="form-label" for="date"><em>Fecha de la reserva</em>: <strong> <?php echo htmlspecialchars($reservation->Date) ?> </strong></label>
                <input type="date" class="form-control text-center" id="date" value="<?php echo htmlspecialchars($reservation->Date) ?>" name="date" required >
            </div>
            <div >
                <button class="btn btn-primary" type="submit">Editar</button>
            </div>
        </form>
    </div>
    </div>
    <div class="d-flex justify-content-center">
        <a href="" class="btn btn-primary m-1">Volver al home</a>
     </div>



    <?php require_once "templates/layout/footer.phtml";?>