<?php require_once "templates/layout/header.phtml";?>
    <div class="card d-flex border border-primary-subtle text-center text-bg-light justify-content-center container-sm mt-2 mb-2">
        <div class="container-sm mt-2 mb-2">
            <form method="POST" action="signupAuth">
                <div class="form-group m-2">
                    <label for="username" class="form-label"><strong><em>Nombre de usuario</em></strong></label>
                    <input type="text" class="form-control text-center" id="username" name="username" required>
                </div>
                <div class="form-group m-2">
                    <label for="password" class="form-label"><strong><em>Contraseña</em></strong></label>
                    <input type="password" class="form-control text-center" id="password" name="password" required>
                </div>
                <button type="sumbit" class="btn btn-primary">Registrar</button>
            </form>
        </div>
    </div>
<?php require_once "templates/layout/footer.phtml";?>