<?php require_once "templates/layout/header.phtml";?>

    
<div class="card d-flex border border-primary-subtle text-center text-bg-light justify-content-center container-sm mt-2 mb-2">
    <div class="container-sm mt-2 mb-2">
        <form method="POST" action="add" id="add">
            <div class="form-group m-2">
                <label for="username">Nombre de usuario</label>
                <select >
                <input type="text" class="form-control" id="username" name="username" required>
            </div>
            <div class="form-group m-2">
                <label for="room_number">Numero de habtiación</label>
                <input type="number" class="form-control" id="room_number" name="room_number" required>
            </div>
            <div class="form-group m-2">
                <label for="date">Fecha</label>
                <input type="date" class="form-control" id="date" name="date" required>
            </div>
            <button type="sumbit" class="btn btn-primary m-2">Reservar</button>
        </form>
    </div>
</div>

    

<?php require_once "templates/layout/footer.phtml"; 