        <?php require_once "templates/layout/header.phtml";?>
      
        <main class="container-sm mt-2 mb-5">
          <section>
      
            <ul class="list-group list-group">

              <!-- Itero el arreglo de reservas e imprimo información de cada una -->
              <?php foreach($reservations as $reservation) : ?>
      
              <li class="list-group-item d-flex justify-content-between  mt-4 border-1 align-items-center">
                <div class="ms-2 me-auto">
                  <div class="fw-bold"><?php echo "Reserva número: " . htmlspecialchars($reservation->ID_Reservation) ?></div>
                        <?php echo "Fecha de reserva: " . htmlspecialchars($reservation->Date) ?> <br>
                        <span class="badge text-bg-primary"> <?php echo "Habitación: " . htmlspecialchars($reservation->Room_number) ?></span>
                </div>
                <div class="d-flex justify-content-evenly">
                  <div>
                    <a href="reservation/<?php echo htmlspecialchars($reservation->ID_Reservation) ?>" class="btn btn-outline-primary m-1">Ver</a><!-- Botón para ver más información de la reserva -->
                  </div>
                  <div >
                    <a href="editReservation/<?php echo htmlspecialchars($reservation->ID_Reservation) ?>" class="btn btn-outline-success m-1">Editar</a> <!-- Botón para editar la reserva-->
                  </div>
                  <div >
                    <a href="delete/<?php echo htmlspecialchars($reservation->ID_Reservation) ?>" class="btn btn-outline-danger m-1">Borrar</a> <!-- Botón para eliminar la reserva-->
                  </div>
                </div>
              </li>
      
              <?php endforeach ?>
      
            </ul>
          </section>
        </main>
        <?php require_once "templates/layout/footer.phtml"; 